const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parse=s=>new Date(s+'T12:00:00');
const iso=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x;};
const monday=d=>add(d,-((d.getDay()+6)%7));
const md=d=>(d.getMonth()+1)+'.'+d.getDate();
const DOW=['월','화','수','목','금'];
let data=null,mode='year',term=0,week=monday(new Date()),request=0;
const token=location.hash.slice(1);
function lessons(date,period){const cls=$('classFilter').value;return data.lessons.filter(L=>L.date===date&&Number(L.period)===period&&(!cls||L.cls===cls));}
function lessonHTML(L,compact=false){const color=/^#[0-9a-f]{6}$/i.test(L.color)?L.color:'#8a94a4';return '<div class="lesson'+(L.status!=='ok'?' off':'')+'" style="--place:'+color+'"><b>'+esc(L.cls)+'</b><small>'+esc(L.place)+(L.ordinal?' · '+esc(L.ordinal)+'차시':'')+'</small>'+(compact?'':(L.status==='ok'&&L.content?'<div class="activity">'+esc(L.content)+'</div>':''))+'</div>';}
function dayEvent(date){return data.days.find(d=>d.date===date);}
function dayHTML(date,period){return lessons(date,period).map(L=>lessonHTML(L)).join('');}
function renderYear(){const range=data.terms[term];$('range').textContent=range?.start&&range?.end?range.start+' ~ '+range.end:'기간 미설정';if(!range?.start||!range?.end){$('content').innerHTML='<p class="empty">아직 이 학기의 수업 기간이 설정되지 않았습니다.</p>';return;}const end=parse(range.end),periods=Math.max(1,Number(data.periods)||1);let html='<table class="yeargrid"><thead><tr><th class="week">주차</th><th class="period">기간</th>';for(let d=0;d<5;d++)for(let p=1;p<=periods;p++)html+='<th>'+DOW[d]+'<small>'+p+'교시</small></th>';html+='</tr></thead><tbody>';let no=0;for(let w=monday(parse(range.start));w<=end;w=add(w,7)){no++;html+='<tr><th class="week">'+no+'주</th><th class="period">'+md(w)+'–'+md(add(w,4))+'</th>';for(let d=0;d<5;d++){const date=iso(add(w,d)),outside=date<range.start||date>range.end,event=dayEvent(date);for(let p=1;p<=periods;p++){const items=outside?[]:lessons(date,p);html+='<td class="'+(outside?'outside':'')+'">'+(outside?'':(event?'<i class="event-dot" title="'+esc(event.label)+'">●</i>':'')+items.map(L=>lessonHTML(L,true)).join(''))+'</td>';}}html+='</tr>';}$('content').innerHTML=html+'</tbody></table>';}
function renderWeek(){const dates=Array.from({length:5},(_,i)=>iso(add(week,i))),periods=Math.max(1,Number(data.periods)||1);$('range').textContent=dates[0]+' ~ '+dates[4];let html='<table class="weekgrid"><thead><tr><th>교시</th>'+dates.map((d,i)=>'<th>'+DOW[i]+' '+md(parse(d))+'<div class="event">'+esc(dayEvent(d)?.label||'')+'</div></th>').join('')+'</tr></thead><tbody>';for(let p=1;p<=periods;p++)html+='<tr><th>'+p+'교시</th>'+dates.map(d=>'<td>'+dayHTML(d,p)+'</td>').join('')+'</tr>';$('content').innerHTML=html+'</tbody></table>';}
function render(){if(!data)return;$('yearTab').setAttribute('aria-pressed',String(mode==='year'));$('weekTab').setAttribute('aria-pressed',String(mode==='week'));$('terms').hidden=mode!=='year';$('weekNav').hidden=mode!=='week';document.querySelectorAll('[data-term]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.term)===term)));mode==='year'?renderYear():renderWeek();}
function clear(text){data=null;$('schedule').hidden=true;$('content').replaceChildren();$('classFilter').innerHTML='<option value="">전체 학급</option>';$('status').textContent=text;}
async function refresh(){const current=++request;if(!/^[a-f0-9]{64}$/.test(token)){clear('공유 링크가 올바르지 않습니다. 선생님께 링크를 다시 받아 주세요.');return;}try{const project=window.PE_FIREBASE_CONFIG?.projectId;const response=await fetch('https://firestore.googleapis.com/v1/projects/'+encodeURIComponent(project)+'/databases/(default)/documents/peShares/'+token,{cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(15000)});if(current!==request)return;if(response.status===404||response.status===403){clear('공유가 중지되었거나 사용할 수 없는 링크입니다.');return;}if(!response.ok)throw Error('fetch-failed');const incoming=JSON.parse((await response.json()).fields.payload.stringValue);if(incoming.version!==1||!Array.isArray(incoming.lessons))throw Error('invalid-data');const first=!data,selected=$('classFilter').value;data=incoming;$('classFilter').innerHTML='<option value="">전체 학급</option>'+data.classes.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('');if(data.classes.includes(selected))$('classFilter').value=selected;if(first){const today=iso(new Date());term=data.terms.findIndex(t=>t.start&&today>=t.start&&today<=t.end);if(term<0)term=0;}$('schedule').hidden=false;$('status').textContent='열람 전용 · 30초마다 최신 내용을 확인합니다.';render();}catch{if(current===request)clear('시간표를 불러오지 못했습니다. 인터넷 연결을 확인하고 새로고침해 주세요.');}}
$('yearTab').onclick=()=>{mode='year';render();};$('weekTab').onclick=()=>{mode='week';render();};$('classFilter').onchange=render;$('terms').onclick=e=>{const b=e.target.closest('[data-term]');if(b){term=Number(b.dataset.term);render();}};$('prev').onclick=()=>{week=add(week,-7);render();};$('next').onclick=()=>{week=add(week,7);render();};$('today').onclick=()=>{week=monday(new Date());render();};$('refresh').onclick=refresh;document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});window.addEventListener('hashchange',()=>location.reload());setInterval(()=>{if(!document.hidden)refresh();},30000);refresh();
